# Generated by Django 5.2.8 on 2025-11-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de Legajo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del Alumno')),
                ('carrera', models.CharField(default='Desarrollo Web', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
